Repository HolmanA/cat-chat, pull requests merged in 2018-10, with the labels that each got.

#60 added enter hotkey to send messages
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.html
Labels: ui

#57 User information component
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.less
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.less
  src/app/ui-module/root/component/root.component.html
  src/app/ui-module/root/component/root.component.less
  src/app/ui-module/ui.module.ts
  src/app/ui-module/user/components/user-details/user-details.component.html
  src/app/ui-module/user/components/user-details/user-details.component.less
  src/app/ui-module/user/components/user-details/user-details.component.ts
  src/app/ui-module/user/components/user/user.component.html
  src/app/ui-module/user/components/user/user.component.less
  src/app/ui-module/user/components/user/user.component.ts
  src/app/ui-module/user/container/user.container.html
  src/app/ui-module/user/container/user.container.ts
  src/less/variables.less
Labels: enhancement, ui

#61 Chat specific new message queues
  src/app/group-chats-module/actions/group-chats.actions.ts
  src/app/group-chats-module/store/group-chats.selectors.ts
  src/app/group-chats-module/store/group-chats.state.ts
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.html
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.ts
  src/app/ui-module/group-chats/container/group-chats.container.html
  src/app/ui-module/group-chats/container/group-chats.container.ts
  src/app/web-socket-module/store/models/message-queue.ts
  src/app/web-socket-module/store/web-socket.selectors.ts
  src/app/web-socket-module/store/web-socket.state.ts
  tslint.json
Labels: enhancement, ui

#63 MULTICHAT
  src/app/group-chats-module/actions/group-chats.actions.ts
  src/app/group-chats-module/group-chats.module.ts
  src/app/group-chats-module/store/group-chats.selectors.ts
  src/app/group-chats-module/store/group-chats.state.ts
  src/app/root-module/app.module.ts
  src/app/selected-chats-module/actions/selected-chats.actions.ts
  src/app/selected-chats-module/selected-chats.module.ts
  src/app/selected-chats-module/store/models/chat-type.ts
  src/app/selected-chats-module/store/models/selected-chat.ts
  src/app/selected-chats-module/store/selected-chats.selectors.ts
  src/app/selected-chats-module/store/selected-chats.state.ts
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.html
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.ts
  src/app/ui-module/group-chats/container/group-chats.container.html
  src/app/ui-module/group-chats/container/group-chats.container.ts
  src/app/ui-module/group-messages/actions/group-messages-container.actions.ts
  src/app/ui-module/group-messages/actions/group-messages-list-item-container.actions.ts
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.ts
  src/app/ui-module/group-messages/container/group-messages-list-item.container.ts
  src/app/ui-module/group-messages/container/group-messages.container.html
  src/app/ui-module/group-messages/container/group-messages.container.ts
  src/app/ui-module/root/component/root.component.html
  src/app/ui-module/root/component/root.component.less
  src/app/ui-module/root/component/root.component.ts
  src/app/ui-module/root/container/root.container.html
  src/app/ui-module/root/container/root.container.ts
  src/app/ui-module/ui.module.ts
  src/app/web-socket-module/store/web-socket.state.ts
  tslint.json
Labels: enhancement, ui

#67 show like cat on hover and fixed styling issues with like counters
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.html
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.less
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.ts
Labels: ui

#68 Added image and video attachments to message list items
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.html
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.less
  src/app/ui-module/group-messages/container/group-messages-list-item.container.html
  src/app/web-socket-module/store/web-socket.state.ts
Labels: enhancement, ui

#72 Continuous integration
  .travis.yml
  angular.json
  e2e/protractor-ci.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  src/app/group-chats-module/services/group-chats.service.spec.ts
  src/app/like-message-module/services/like-message.service.spec.ts
  src/app/root-module/components/app.component.spec.ts
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.ts
  src/app/ui-module/group-messages/components/message-text/message-text.component.ts
  src/app/user-module/services/user.service.spec.ts
  src/karma.conf.js
Labels: enhancement
