Repository HolmanA/cat-chat, pull requests merged in 2018-09, with the labels that each got.

#28 Connected new message input and send button to endpoint
  package-lock.json
  package.json
  src/app/group-chats-module/actions/group-chats.actions.ts
  src/app/group-chats-module/store/group-chats.state.ts
Labels: enhancement

#29 Creating a new message websocket
  src/app/group-chats-module/services/group-chats.service.ts
  src/app/group-chats-module/store/group-chats.state.ts
  src/app/root-module/actions/app.actions.ts
  src/app/root-module/app.module.ts
  src/app/root-module/components/app.component.html
  src/app/root-module/components/app.component.less
  src/app/root-module/components/app.component.spec.ts
  src/app/root-module/components/app.component.ts
  src/app/root-module/services/auth/auth.interceptor.ts
  src/app/root-module/services/auth/auth.service.ts
  src/app/ui-module/group-chats/actions/group-chats-container.actions.ts
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.html
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.ts
  src/app/ui-module/group-chats/container/group-chats.container.html
  src/app/ui-module/group-chats/container/group-chats.container.ts
  src/app/ui-module/group-messages/actions/group-messages-container.actions.ts
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.html
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.less
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.ts
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.less
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.ts
  src/app/ui-module/group-messages/container/group-messages.container.html
  src/app/ui-module/group-messages/container/group-messages.container.ts
  src/app/ui-module/root/actions/root-container.actions.ts
  src/app/ui-module/root/component/root.component.html
  src/app/ui-module/root/component/root.component.less
  src/app/ui-module/root/component/root.component.ts
  src/app/ui-module/root/container/root.container.html
  src/app/ui-module/root/container/root.container.ts
  src/app/ui-module/ui.module.ts
  src/app/user-module/actions/user.actions.ts
  src/app/user-module/services/models/update-user.request.ts
  src/app/user-module/services/user.service.spec.ts
  src/app/user-module/services/user.service.ts
  src/app/user-module/store/user.selectors.ts
  src/app/user-module/store/user.state.ts
  src/app/user-module/user.module.ts
  src/app/web-socket-module/actions/web-socket.actions.ts
  src/app/web-socket-module/services/web-socket.service.ts
  src/app/web-socket-module/store/web-socket.selectors.ts
  src/app/web-socket-module/store/web-socket.state.ts
  src/app/web-socket-module/web-socket.module.ts
Labels: enhancement

#36 #20 Infinite Scroll Messages
  src/app/group-chats-module/actions/group-chats.actions.ts
  src/app/group-chats-module/services/group-chats.service.ts
  src/app/group-chats-module/services/models/groups/change-owners.request.ts
  src/app/group-chats-module/services/models/groups/create-group.request.ts
  src/app/group-chats-module/services/models/groups/destroy-group.request.ts
  src/app/group-chats-module/services/models/groups/fetch-group.request.ts
  src/app/group-chats-module/services/models/groups/fetch-groups.request.ts
  src/app/group-chats-module/services/models/groups/join-group.request.ts
  src/app/group-chats-module/services/models/groups/re-join-group.request.ts
  src/app/group-chats-module/services/models/groups/update-group.request.ts
  src/app/group-chats-module/services/models/members/add-members-results.request.ts
  src/app/group-chats-module/services/models/members/add-members.request.ts
  src/app/group-chats-module/services/models/members/remove-member.request.ts
  src/app/group-chats-module/services/models/memberships/update-membership.request.ts
  src/app/group-chats-module/services/models/messages/create-message.request.ts
  src/app/group-chats-module/services/models/messages/fetch-messages.request.ts
  src/app/group-chats-module/store/group-chats.selectors.ts
  src/app/group-chats-module/store/group-chats.state.ts
  src/app/root-module/actions/app.actions.ts
  src/app/root-module/components/app.component.ts
  src/app/root-module/services/auth/auth.service.ts
  src/app/ui-module/group-chats/actions/group-chats-container.actions.ts
  src/app/ui-module/group-chats/container/group-chats.container.ts
  src/app/ui-module/group-messages/actions/group-messages-container.actions.ts
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.ts
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.ts
  src/app/ui-module/group-messages/container/group-messages.container.html
  src/app/ui-module/group-messages/container/group-messages.container.ts
  src/app/ui-module/root/actions/root-container.actions.ts
  src/app/user-module/actions/user.actions.ts
  src/app/user-module/services/models/update-user.request.ts
  src/app/user-module/services/user.service.ts
  src/app/user-module/store/user.selectors.ts
  src/app/user-module/store/user.state.ts
  src/app/user-module/user.module.ts
  src/app/web-socket-module/actions/web-socket.actions.ts
  src/app/web-socket-module/services/web-socket.service.ts
  src/app/web-socket-module/store/web-socket.selectors.ts
  src/app/web-socket-module/store/web-socket.state.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/tslint.json
  tslint.json
Labels: enhancement

#38 Huge ui update. Much better than before
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.html
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.ts
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.html
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.less
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.less
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.ts
  src/app/ui-module/group-messages/container/group-messages.container.html
  src/app/ui-module/group-messages/container/group-messages.container.ts
  src/app/ui-module/root/component/root.component.html
  src/app/ui-module/root/component/root.component.less
Labels: enhancement, ui

#39 Update Stage
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.html
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.ts
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.html
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.less
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.less
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.ts
  src/app/ui-module/group-messages/container/group-messages.container.html
  src/app/ui-module/group-messages/container/group-messages.container.ts
  src/app/ui-module/root/component/root.component.html
  src/app/ui-module/root/component/root.component.less
Labels: enhancement, stage, ui

#46 Like message functionality
  src/app/group-chats-module/actions/group-chats.actions.ts
  src/app/group-chats-module/group-chats.module.ts
  src/app/group-chats-module/store/group-chats.state.ts
  src/app/like-message-module/like-message.module.ts
  src/app/like-message-module/services/like-message.service.spec.ts
  src/app/like-message-module/services/like-message.service.ts
  src/app/like-message-module/services/models/like-message.request.ts
  src/app/like-message-module/services/models/unlike-message.request.ts
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-messages/actions/group-messages-list-item-container.actions.ts
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.less
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.html
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.less
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.ts
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.less
  src/app/ui-module/group-messages/container/group-messages-list-item.container.html
  src/app/ui-module/group-messages/container/group-messages-list-item.container.ts
  src/app/ui-module/ui.module.ts
  src/assets/like-cat-active.png
  src/assets/like-cat.png
  src/index.html
Labels: enhancement, ui

#48 Added Like functionality
  src/app/group-chats-module/actions/group-chats.actions.ts
  src/app/group-chats-module/group-chats.module.ts
  src/app/group-chats-module/store/group-chats.state.ts
  src/app/like-message-module/like-message.module.ts
  src/app/like-message-module/services/like-message.service.spec.ts
  src/app/like-message-module/services/like-message.service.ts
  src/app/like-message-module/services/models/like-message.request.ts
  src/app/like-message-module/services/models/unlike-message.request.ts
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.less
  src/app/ui-module/group-messages/actions/group-messages-list-item-container.actions.ts
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.less
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.html
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.less
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.ts
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.html
  src/app/ui-module/group-messages/components/group-messages-list/group-messages-list.component.less
  src/app/ui-module/group-messages/container/group-messages-list-item.container.html
  src/app/ui-module/group-messages/container/group-messages-list-item.container.ts
  src/app/ui-module/ui.module.ts
  src/assets/like-cat-active.png
  src/assets/like-cat.png
  src/index.html
Labels: enhancement, stage, ui

#52 Clear new message box after send feature
  src/app/ui-module/group-messages/components/group-message-input/group-message-input.component.ts
Labels: ui

#53 fixed datetime display to something user friendly
  src/app/ui-module/group-messages/components/group-messages-list-item/group-messages-list-item.component.html
Labels: ui

#54 Trim message text
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.html
  src/app/ui-module/group-chats/components/group-chats-list/group-chats-list.component.ts
Labels: ui
